### ISSUE TITLE
Cannot login customgpt.thesamur.ai

### ISSUE THREAD

**Issue by glinft** [SamurAIGPT/Open-Custom-GPT#10]
Login with google, then redirect to localhost:5000.
Seems to not configure google login correctly.

**Comment by Anil-matcha** [comment]
This has been fixed now

**Comment by OneTop4458** [comment]
I'm still getting a 500 error and can't log in.

**Comment by Anil-matcha** [comment]
@OneTop4458 Do check again, must be fixed now

**Comment by OneTop4458** [comment]
I tried it now and it works fine
Thank you.
