### ISSUE TITLE
The app keeps asking for API Key every time the page is refreshed

### ISSUE THREAD

**Issue by ascensus-mdb** [SamurAIGPT/Open-Custom-GPT#11]
Hi. Thank you very much for this projects, it's very useful.

Everything works fine, but there seems to be annoying bug - every time I refresh the browser I see the form asking me to provide OpenAI key, even if I provided it before and I already have a working assistant chat.

![image](https://github.com/SamurAIGPT/Open-Custom-GPT/assets/15121333/d9bbcce0-4916-4b8f-91d4-ce16e0af863e)

Any ideas how to prevent it?

**Comment by Anil-matcha** [comment]
We will add a fix for this in the next update

**Comment by ascensus-mdb** [comment]
Great, thanks. By the way - wouldn't it be better and safer to store the api key in an .env file?

**Comment by Rohanmrao** [comment]
While you develop the fix, is there a temporary workaround to this ?

**Comment by Anil-matcha** [comment]
@ascensus-mdb @Rohanmrao This has been fixed now
