### ISSUE TITLE
Assistants isn't loading

### ISSUE THREAD

**Issue by puresoul** [SamurAIGPT/Open-Custom-GPT#16]
Hi,

downloaded a HEAD version, then npm install, insert api key, but on next screen have just create assistant so it's not list already created ones and if I click on "Create new one" I get

   Application error: a client-side exception has occurred (see the browser console for more information).

In console:

Uncaught SyntaxError: redeclaration of var Audio 749-437c88a29d01f3f9.js:9:22911note: Previously declared at line 6, column 23254749-437c88a29d01f3f9.js:6:23254

ChunkLoadError: Loading chunk 749 failed.
(missing: http://127.0.0.1:3000/_next/static/chunks/749-437c88a29d01f3f9.js)
    NextJS 40
        j
        e
        e
        n
        t
        t
        promise callback*U
        createFromFetch
        promise callback*7950/t.createFromFetch
        f
        E
        rb
        iU
        o2
        oB
        t
        oB
        C
        1756
        s
        8261
        s
        4417
        s
        4887
        s
        4040
        s
        811
        s
        2019
        r
        r
        2019
        s
        n
        <anonymous>
        O
        c
        <anonymous>
472-69984e29036e4540.js:1:3763

Have some clue, what I'am doing wrong?

Thanks

**Comment by Anil-matcha** [comment]
Can you do a npm run build before doing a run ?

**Comment by mledwards** [comment]
I'm getting this too, when running `npm run build && npm start`

**Comment by mledwards** [comment]
Solution here: https://github.com/SamurAIGPT/Open-Custom-GPT/issues/24
