### ISSUE TITLE
Issues running npm run start or npm start 

### ISSUE THREAD

**Issue by hcdgsv** [SamurAIGPT/Open-Custom-GPT#21]
I get an error while running the application in a production environment on my server:
(previously, I have run on the server: npm run build)
npm run start or npm start

I am attaching some screenshots.
<img width="1728" alt="Screenshot 2024-01-15 at 00 17 29" src="https://github.com/SamurAIGPT/Open-Custom-GPT/assets/145182858/c87d6c00-ed2f-4561-a052-bc20f5187cab">
<img width="483" alt="Screenshot 2024-01-15 at 00 17 55" src="https://github.com/SamurAIGPT/Open-Custom-GPT/assets/145182858/ec11d987-3089-4011-b794-a65b5d8d4fb5">
<img width="386" alt="Screenshot 2024-01-15 at 00 18 02" src="https://github.com/SamurAIGPT/Open-Custom-GPT/assets/145182858/1f0c57dc-a14f-481e-9aa9-2b805c66cd5d">

**Comment by Anil-matcha** [comment]
It looks like a not relevant error. Have you observed any issue loading the page

**Comment by biserd** [comment]
I have the same error, and the UI is not super helpful
![image](https://github.com/SamurAIGPT/Open-Custom-GPT/assets/4376132/847abe50-2f31-42d3-9a56-6b7b68a9f8f5)

**Comment by biserd** [comment]
My vercel is https://open-custom-gpt-peach.vercel.app/

**Comment by hcdgsv** [comment]
> It looks like a not relevant error. Have you observed any issue loading the page

The only page that is loading is the main page and if i clic to my chat or if i want to add another i got the error

also if i run the server with npm run dev is working propperly

**Comment by adamzhang1987** [comment]
I got the same error the first time and solved it using the latest next.js version, which is 14.1.0.

**Comment by Anil-matcha** [comment]
@hcdgsv Please update your nextjs version
