### ISSUE TITLE
suggestion - sample to programmatically update knowledge base

### ISSUE THREAD

**Issue by johndpope** [SamurAIGPT/Open-Custom-GPT#23]
I customized my openapi gpt with some data - then hit a wall when I wanted to programatically update the knowledge base. perhaps the sample would be fit a lot of users - use-case for using this repo too. 

How can this be done with this repo?
I guess there's many options - do we have to use pinecone? or is there a way to do a custom scheduled tasks to replace a file?
![Screenshot from 2024-01-24 10-12-18](https://github.com/SamurAIGPT/Open-Custom-GPT/assets/289994/25c15440-36d0-489c-9440-080299102033)

I guess thinking out loud - I kind of want a page - admin panel that just helps with this kind of steps - or spoon feeds user on this use case.

**Comment by Anil-matcha** [comment]
The ideal way for this would be to have a function call which can invoke a dynamic RAG system which has been implemented separately and has the capability to update it's knowledge dynamically
