### ISSUE TITLE
Way to expensive

### ISSUE THREAD

**Issue by AmberWolf16** [SamurAIGPT/Open-Custom-GPT#31]
I just made a custom GPT and looked for options to embed it into my website and found this. At first, I was happy because this was one of the only functioning things I found. Then, I looked at the pricing and found out you have to pay 90 dollars! That is way too much for something like this. If you ask me, this programmer should lower the price for something that is very slow.

**Comment by Anil-matcha** [comment]
Hi

Thanks for sharing your feedback, the pricing is 90$ per year but if don't want to pay that much, you can choose a monthly plan at 9$/month

**Comment by Anil-matcha** [comment]
Also speed has been improved now as streaming is supported

**Comment by timstew** [comment]
is streaming supported in this codebase? or just on the hosted version?

**Comment by Anil-matcha** [comment]
@timstew Currently only in the hosted version as it needs to be run on vercel edge function
