### ISSUE TITLE
Is it possible to save multiple agents?

### ISSUE THREAD

**Issue by JeremiLorenti** [SamurAIGPT/Open-Custom-GPT#8]
I seem to only be able to generate one agent at a time. Will there be added functionality to manage multiple agents?

**Comment by Anil-matcha** [comment]
Adding it in the next update in 2-3 days

**Comment by andersborgabiro** [comment]
The latter is actually easier, as it takes away the need to store information about assistants locally, unless you add meta data that's unique to Open-Custom-GPT. The only issue I've found is that the assistants request is a bit slow. Might be temporary though.

**Comment by Anil-matcha** [comment]
Fixed now in latest commit with support for multiple agents creation from dashboard
