### ISSUE TITLE
API Keys Exposed Publicly in Shared Links

### ISSUE THREAD

**Issue by Keldos-Li** [SamurAIGPT/Open-Custom-GPT#9]
Hi, the current sharing mechanism reveals API keys publicly in shared links, posing a critical security threat. I think we need a new, secure linking method.

**Comment by Anil-matcha** [comment]
Will release an update next to fix this

**Comment by Anil-matcha** [comment]
Fixed now and allows user to input their api key before using the created assistant

**Comment by mledwards** [comment]
Hmm, this could have been fixed in a way that didn't stop the share link being unusable unless someone has a paid account?
